name: Merge PRs with label action
description: Merges open PRs with a lable and created by the repos owner
author: pdamianik

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  token:
    description: the github auth token
    required: true
  label:
    description: prs with this label will be merged
    required: true

# Define your outputs here.
outputs: {}

runs:
  using: node20
  main: dist/index.js
